//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Model.Schema.EIVO {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CancelInvoiceRoot {
        
        private string companyBanField;
        
        private CancelInvoiceRootCancelInvoice[] cancelInvoiceField;
        
        /// <remarks/>
        public string CompanyBan {
            get {
                return this.companyBanField;
            }
            set {
                this.companyBanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CancelInvoice")]
        public CancelInvoiceRootCancelInvoice[] CancelInvoice {
            get {
                return this.cancelInvoiceField;
            }
            set {
                this.cancelInvoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CancelInvoiceRootCancelInvoice {
        
        private string cancelInvoiceNumberField;
        
        private string invoiceDateField;
        
        private string sellerIdField;
        
        private string cancelDateField;
        
        private string cancelTimeField;
        
        private string returnTaxDocumentNumberField;
        
        private string remarkField;
        
        /// <remarks/>
        public string CancelInvoiceNumber {
            get {
                return this.cancelInvoiceNumberField;
            }
            set {
                this.cancelInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string SellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
            }
        }
        
        /// <remarks/>
        public string CancelDate {
            get {
                return this.cancelDateField;
            }
            set {
                this.cancelDateField = value;
            }
        }
        
        /// <remarks/>
        public string CancelTime {
            get {
                return this.cancelTimeField;
            }
            set {
                this.cancelTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnTaxDocumentNumber {
            get {
                return this.returnTaxDocumentNumberField;
            }
            set {
                this.returnTaxDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
}
