//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.1433
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uxnet.Web.Module.Common {
    
    
    /// <summary>
    /// ExceptionHandler 類別。
    /// </summary>
    /// <remarks>
    /// 自動產生的類別。
    /// </remarks>
    public partial class ExceptionHandler {
    }
}
