//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.2.23\\sqlexpress,1433;Initial Catalog=EIVO05Prod;Persist Securi" +
            "ty Info=True;User ID=eivo;Password=eivoeivo")]
        public string eInvoiceConnectionString {
            get {
                return ((string)(this["eInvoiceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SessionTimeout {
            get {
                return ((double)(this["SessionTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Ap2APPilot\\ERPOutBox")]
        public string GOVPlatformOutbound {
            get {
                return ((string)(this["GOVPlatformOutbound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Ap2APPilot\\ebMSInBox")]
        public string GOVPlatformResponse {
            get {
                return ((string)(this["GOVPlatformResponse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EINVTurnkey\\UpCast\\B2CSTORAGE\\A1401\\SRC")]
        public string A1401Outbound {
            get {
                return ((string)(this["A1401Outbound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EINVTurnkey\\UpCast\\B2CSTORAGE\\B1401\\SRC")]
        public string B1401Outbound {
            get {
                return ((string)(this["B1401Outbound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EINVTurnkey\\UpCast\\B2CSTORAGE\\A0501\\SRC")]
        public string A0501Outbound {
            get {
                return ((string)(this["A0501Outbound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EINVTurnkey\\UpCast\\B2CSTORAGE\\B0501\\SRC")]
        public string B0501Outbound {
            get {
                return ((string)(this["B0501Outbound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EINVTurnkey\\UpCast\\B2CSTORAGE\\A0401\\SRC")]
        public string A0401Outbound {
            get {
                return ((string)(this["A0401Outbound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EINVTurnkey\\UpCast\\B2CSTORAGE\\B0401\\SRC")]
        public string B0401Outbound {
            get {
                return ((string)(this["B0401Outbound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EINVTurnkey\\UpCast\\B2PMESSAGE\\E0402\\SRC")]
        public string E0402Outbound {
            get {
                return ((string)(this["E0402Outbound"]));
            }
        }
    }
}
